name: Build Arduino Sketch

on:
  push:
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.h'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install board platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Install libraries
        run: |
          arduino-cli lib install "FastLED"
          arduino-cli lib install "NewPing"

      - name: Compile Sketch (Mega 2560)
        run: |
          arduino-cli compile --fqbn arduino:avr:mega \
            ./Digital_RGB_LED
