name: Arduino Lint

on:
  pull_request:
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.h'
      - 'library.properties'
      - '.github/workflows/arduino-lint.yml'

jobs:
  arduino-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Arduino Lint
        uses: arduino/arduino-lint-action@v2
        with:
          libraries: |
            libraries/*
          sketch: Digital_RGB_LED/Digital_RGB_LED.ino
          additional-urls: |
            https://raw.githubusercontent.com/arduino/library-registry/main/library_index.json